POST http://localhost:9080/register HTTP/1.1
content-Type: application/json

{
    "username": "testuser12",
    "password": "testpass12312",
    "email": "test12@example.com",
    "name": "Test12 User"
}

###

POST http://localhost:9080/login HTTP/1.1
content-Type: application/json

{
    "email": "test12@example.com",
    "password": "testpass12312"
}

###

GET http://localhost:9080/get_posts HTTP/1.1
content-Type: application/json



###

GET http://localhost:9080/get_user_and_profile
content-Type: application/json

{
    "token": "ebf686caeb3491815418d7a1d6d8592c98174c44092f5606b7cbe0fba7fb18b9"
}


###
POST http://localhost:9080/update_profile_data
content-Type: application/json

{
    "token": "e99eb6b5895b40442484cc2bd7f7723b9538dbd9c30cc26e2812d1f3ee6a6d8a",
    "bio": "Hi",
    "currentPost": "CTO",
    "pastWork": [
        {
            "company": "Microsoft",
            "position": "Software Engineer",
            "years": "2+"
        }
    ],
    "education": [
        {
            "school": "IIIT",
            "degree": "B.Tech",
            "fieldOfStudy": "2024-2025"
        }
    ]

}



###

GET http://localhost:9080/user/get_all_users
Content-Type: application/json